# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      id: install-packages
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get update
        sudo apt-get install -y openfoam2106-default libopenmpi-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install -v
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        set +o pipefail
        source /usr/lib/openfoam/openfoam2106/etc/bashrc || true
        poetry run pytest
      shell: bash
